spring.application.name=backend

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/LMS_matricula
spring.datasource.username=postgres
<<<<<<< HEAD
spring.datasource.password=root
=======
spring.datasource.password=1234
>>>>>>> deb2985ea8a5b3ce8da58274fc83ae8c643ba017

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Metabase
metabase.url=http://localhost:3000
metabase.username=sagradafamilia@gmail.com
metabase.password=sagradafamilia123