spring.application.name=backend

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/LMS_matricula
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Metabase
metabase.url=http://localhost:3000
metabase.username=sagradafamilia@gmail.com
metabase.password=sagradafamilia123